//
//  ViewModifier.swift
//  BoxJs
//
//  Created by Senku on 7/19/24.
//

import Foundation
import SwiftUI
import Transmission
import UIKit

struct BackgroundImageModifier: ViewModifier {
    func body(content: Content) -> some View {
        ZStack {
            Image("1")
                .resizable()
                .scaledToFill()
                .edgesIgnoringSafeArea(.all)
            content
        }
    }
}


extension View {
    func backgroundImage() -> some View {
        self.modifier(BackgroundImageModifier())
    }
}


extension Color {
    init(hex: String) {
        let scanner = Scanner(string: hex)
        _ = scanner.scanString("#")

        var rgba: UInt64 = 0
        scanner.scanHexInt64(&rgba)

        let length = hex.replacingOccurrences(of: "#", with: "").count
        let r, g, b, a: Double
        if length >= 8 {
            r = Double((rgba & 0xFF000000) >> 24) / 255.0
            g = Double((rgba & 0x00FF0000) >> 16) / 255.0
            b = Double((rgba & 0x0000FF00) >> 8) / 255.0
            a = Double(rgba & 0x000000FF) / 255.0
        } else {
            r = Double((rgba & 0xFF0000) >> 16) / 255.0
            g = Double((rgba & 0x00FF00) >> 8) / 255.0
            b = Double(rgba & 0x0000FF) / 255.0
            a = 1.0
        }

        self.init(red: r, green: g, blue: b, opacity: a)
    }

    func toHex() -> String {
        guard let components = UIColor(self).cgColor.components else { return "#000000" }
        let r = Int((components[safe: 0] ?? 0) * 255)
        let g = Int((components[safe: 1] ?? 0) * 255)
        let b = Int((components[safe: 2] ?? 0) * 255)
        return String(format: "#%02X%02X%02X", r, g, b)
    }

    // MARK: - Design Token Aliases
    // Most tokens are auto-generated by Xcode from Asset Catalog (GeneratedAssetSymbols).
    // Only aliases for renamed tokens are kept here.
    static let accent = Color.accentBlue

    /// Adaptive page gradient colors (light: subtle purple, dark: deep navy)
    static let pageGradientColors: [Color] = [.gradientTop, .gradientMid, .gradientBottom]
}

private extension Array {
    subscript(safe index: Int) -> Element? {
        indices.contains(index) ? self[index] : nil
    }
}

// MARK: - Enable swipe back gesture when navigation bar is hidden

private struct SwipeBackEnabler: UIViewRepresentable {
    func makeUIView(context: Context) -> UIView {
        let view = SwipeBackView()
        return view
    }
    func updateUIView(_ uiView: UIView, context: Context) {}
}

private class SwipeBackView: UIView {
    override func didMoveToWindow() {
        super.didMoveToWindow()
        enableSwipeBack()
    }

    override func layoutSubviews() {
        super.layoutSubviews()
        enableSwipeBack()
    }

    private func enableSwipeBack() {
        guard let nav = findNavigationController() else { return }
        nav.interactivePopGestureRecognizer?.isEnabled = true
        nav.interactivePopGestureRecognizer?.delegate = nil
    }

    private func findNavigationController() -> UINavigationController? {
        var responder: UIResponder? = self
        while let next = responder?.next {
            if let nav = next as? UINavigationController {
                return nav
            }
            responder = next
        }
        return nil
    }
}

extension View {
    func enableSwipeBack() -> some View {
        background(SwipeBackEnabler())
    }
}

// MARK: - iOS 15 Navigation Compatibility

@ViewBuilder
func neboxNavigationContainer<Content: View>(@ViewBuilder _ content: () -> Content) -> some View {
    if #available(iOS 16.0, *) {
        NavigationStack {
            content()
        }
    } else {
        NavigationView {
            content()
        }
        .navigationViewStyle(StackNavigationViewStyle())
    }
}

extension View {
    @ViewBuilder
    func neboxHiddenNavigationBar() -> some View {
        if #available(iOS 16.0, *) {
            self
                .toolbar(.hidden, for: .navigationBar)
                .toolbarBackground(.hidden, for: .navigationBar)
        } else {
            self
                .navigationBarTitle("", displayMode: .inline)
                .navigationBarHidden(true)
        }
    }

    /// Pushes `destination` using Transmission's `DestinationLink` zoom transition.
    ///
    /// `.zoomIfAvailable` gives the real zoom on iOS 18+ and degrades to the default
    /// push below that, so no `#available` split is needed here.
    ///
    /// Transmission zooms from **the view this modifier is attached to** — there is no
    /// `Namespace` / `matchedTransitionSource` pairing like SwiftUI's own zoom. Attach
    /// it to the individual cell or row, never to the page as a whole, otherwise the
    /// animation originates from the full screen.
    func neboxNavigationDestination<Destination: View>(
        isPresented: Binding<Bool>,
        @ViewBuilder destination: @escaping () -> Destination
    ) -> some View {
        self.destination(
            transition: .zoomIfAvailable,
            isPresented: isPresented,
            destination: destination
        )
    }

    @ViewBuilder
    func neboxMediumSheet() -> some View {
        if #available(iOS 16.0, *) {
            self
                .presentationDetents([.medium])
                .presentationDragIndicator(.visible)
        } else {
            self
        }
    }

    @ViewBuilder
    func neboxSheetPresentation() -> some View {
        if #available(iOS 16.0, *) {
            self
                .presentationDetents([.medium, .large])
                .presentationDragIndicator(.visible)
        } else {
            self
        }
    }

    @ViewBuilder
    func neboxHideTabBar() -> some View {
        if #available(iOS 26.0, *) {
            self
                .toolbar(.hidden, for: .tabBar)
        } else {
            self
                .preference(key: NEBoxHideTabBarPreferenceKey.self, value: true)
        }
    }

}

struct NEBoxHideTabBarPreferenceKey: PreferenceKey {
    static var defaultValue: Bool = false

    static func reduce(value: inout Bool, nextValue: () -> Bool) {
        value = value || nextValue()
    }
}

// MARK: - Keyboard Dismissal

struct ScrollDismissKeyboardModifier: ViewModifier {
    func body(content: Content) -> some View {
        if #available(iOS 16.0, *) {
            content.scrollDismissesKeyboard(.interactively)
        } else {
            content
        }
    }
}

// MARK: - iOS 26 Liquid Glass Modifiers
//
// The Liquid Glass APIs (`glassEffect`, `.glassProminent`, `tabBarMinimizeBehavior`,
// …) only *exist* in the iOS 26 SDK, which ships with Xcode 26 / Swift 6.2.
// `#available` is a **runtime** check — it still requires the symbol to exist at
// compile time, so it cannot guard these on an older SDK. Building on Xcode 16
// (iOS 18 SDK, Swift 6.1) therefore fails with "no member 'glassEffect'".
//
// `#if compiler(>=6.2)` is the **compile-time** guard: Swift 6.2 is the first
// toolchain (Xcode 26) whose SDK declares these symbols. Every Liquid Glass call
// site must sit inside `#if compiler(>=6.2)` *and* an `#available` check — the
// former so older Xcode can compile the file at all, the latter so older iOS
// still takes the fallback path at runtime.

/// Glass effect for floating tab bars and pill-shaped containers
struct GlassTabBarModifier: ViewModifier {
    /// Telegram's tab group and search pill are both fully rounded, so callers pass
    /// their own radius (half the height) rather than sharing one fixed value.
    var cornerRadius: CGFloat = 28

    func body(content: Content) -> some View {
        #if compiler(>=6.2)
        if #available(iOS 26.0, *) {
            content
                .glassEffect(.regular.interactive(), in: .rect(cornerRadius: cornerRadius))
        } else {
            legacyBackground(content)
        }
        #else
        legacyBackground(content)
        #endif
    }

    @ViewBuilder
    private func legacyBackground(_ content: Content) -> some View {
        content
            .background(RelayGlassBackground(cornerRadius: cornerRadius))
    }
}

/// Glass effect for card containers
struct GlassCardModifier: ViewModifier {
    var cornerRadius: CGFloat = 16

    func body(content: Content) -> some View {
        #if compiler(>=6.2)
        if #available(iOS 26.0, *) {
            content
                .glassEffect(.regular, in: .rect(cornerRadius: cornerRadius))
        } else {
            legacyBackground(content)
        }
        #else
        legacyBackground(content)
        #endif
    }

    @ViewBuilder
    private func legacyBackground(_ content: Content) -> some View {
        content
            .background(
                RoundedRectangle(cornerRadius: cornerRadius, style: .continuous)
                    .fill(Color(.secondarySystemGroupedBackground))
            )
    }
}

/// Glass effect for prominent buttons
struct GlassButtonModifier: ViewModifier {
    let isDisabled: Bool

    func body(content: Content) -> some View {
        #if compiler(>=6.2)
        if #available(iOS 26.0, *) {
            content
                .buttonStyle(.glassProminent)
                .opacity(isDisabled ? 0.5 : 1.0)
        } else {
            legacyBackground(content)
        }
        #else
        legacyBackground(content)
        #endif
    }

    @ViewBuilder
    private func legacyBackground(_ content: Content) -> some View {
        content
            .foregroundColor(.white)
            .background(
                RoundedRectangle(cornerRadius: 12, style: .continuous)
                    .fill(isDisabled ? Color.gray.opacity(0.4) : Color.accentColor)
            )
    }
}

extension View {
    func glassTabBar(cornerRadius: CGFloat = 28) -> some View {
        modifier(GlassTabBarModifier(cornerRadius: cornerRadius))
    }

    func glassCard(cornerRadius: CGFloat = 16) -> some View {
        modifier(GlassCardModifier(cornerRadius: cornerRadius))
    }

    func glassButton(isDisabled: Bool = false) -> some View {
        modifier(GlassButtonModifier(isDisabled: isDisabled))
    }
}

// MARK: - Tab bar colors

/// Single place to tweak **native `TabView`** (`.tint` + `UITabBar` tints) and the **custom floating bar** on older iOS.
enum NEBoxTabBarPalette {
    static let selected = Color.accentBlue
    static let unselected = Color.textInactive

    /// UIKit equivalents — adaptive via Asset Catalog.
    static let selectedUIKit = UIColor(.accentBlue)
    static let unselectedUIKit = UIColor(.textInactive)
}

// MARK: - iOS Version Adaptive Utilities

/// Returns the appropriate bottom inset for content views
/// - iOS 26+: Native TabView with Liquid Glass tab bar (~90pt)
/// - iOS < 26: Account for custom floating tab bar (110pt)
func adaptiveBottomInset() -> CGFloat {
    if #available(iOS 26.0, *) {
        return 90
    } else {
        return 110
    }
}

// MARK: - iOS 26 Tab bar (Liquid Glass)

extension View {
    /// Dismiss the keyboard when the user scrolls the container, using the
    /// system-native `scrollDismissesKeyboard` API (iOS 16+). Replaces manual
    /// tap-gesture / `resignFirstResponder` focus workarounds on scroll views.
    /// No-ops on iOS 15, where the API is unavailable.
    @ViewBuilder
    func neboxDismissKeyboardOnScroll() -> some View {
        if #available(iOS 16.0, *) {
            self.scrollDismissesKeyboard(.immediately)
        } else {
            self
        }
    }
}

extension View {
    /// Per-tab toolbar chrome for native `TabView` on iOS 26+ (attach to each tab’s root, not `TabView`).
    @ViewBuilder
    func neboxLiquidGlassTabBarChrome() -> some View {
        #if compiler(>=6.2)
        if #available(iOS 26.0, *) {
            self
                .toolbarBackground(
                    LinearGradient(
                        colors: Color.pageGradientColors,
                        startPoint: .top,
                        endPoint: .bottom
                    ),
                    for: .tabBar
                )
                .toolbarBackgroundVisibility(.visible, for: .tabBar)
        } else {
            self
        }
        #else
        self
        #endif
    }
}
