//
//  ViewModifier.swift
//  BoxJs
//
//  Created by Senku on 7/19/24.
//

import Foundation
import SwiftUI
import Transmission
import UIKit

struct BackgroundImageModifier: ViewModifier {
    func body(content: Content) -> some View {
        ZStack {
            Image("1")
                .resizable()
                .scaledToFill()
                .edgesIgnoringSafeArea(.all)
            content
        }
    }
}


extension View {
    func backgroundImage() -> some View {
        self.modifier(BackgroundImageModifier())
    }
}


extension Color {
    /// Lenient hex parse — unparseable input becomes black.
    ///
    /// 实现委托给 `UIColor(validHex:)`，两边共用一个解析器：否则同一个
    /// 主题色串在色块（这里）和实际强调色（`ThemePalette`）上会解析成
    /// 两种颜色，而且这份旧实现没有三位简写分支，`#abc` 会被当成
    /// `0x000ABC` 读成近黑色。要区分「非法」和「黑色」就直接用
    /// `UIColor(validHex:)`。
    init(hex: String) {
        self = Color(UIColor(validHex: hex) ?? .black)
    }

    func toHex() -> String {
        // ⚠️ 必须先转到 sRGB 再取分量，不能直接读 `cgColor.components`。
        // 系统 `ColorPicker` 工作在 Display P3，`UIColor(Color)` 会**保留** P3 而不是
        // 转换；P3 里的饱和色在 sRGB 口径下会落到 0–1 之外（实测琥珀色拿到
        // `[1.013, 0.721, -0.254]`）。按原样 `*255` 格式化会吐出 `#102B8FFFFFFBF`
        // 这种 13 位畸形串，再解析回来就是另一个颜色——表现为拖一个通道另外两个
        // 通道乱跳。转换 + 夹取到 0–1 之后往返才稳定。
        let srgb = UIColor(self).resolvedSRGBComponents
        // 四舍五入而非截断：`Int(0.733 * 255)` = 186 (BA)，而原色是 187 (BB)，
        // 每次经 ColorPicker 往返都会掉一格，主题色会慢慢漂移。
        let r = Int((srgb.red * 255).rounded())
        let g = Int((srgb.green * 255).rounded())
        let b = Int((srgb.blue * 255).rounded())
        return String(format: "#%02X%02X%02X", r, g, b)
    }

    // MARK: - Design Token Aliases
    // Most tokens are auto-generated by Xcode from Asset Catalog (GeneratedAssetSymbols).
    // Only aliases for renamed tokens are kept here.

    /// 主题色。用户在 BoxJs 里选过就用它，否则回落到 `accentBlue` token。
    ///
    /// 计算属性而非 `static let`：主题色是运行时可变的，常量会把首次取到的
    /// 颜色永久固化。
    ///
    /// - Important: 这是个**不带订阅**的快照读。绝大多数界面靠根上的
    ///   `relayThemedAccent()`（`.tint`）或所在页面重算来跟上变化；如果某个
    ///   视图需要在主题色变化时**立刻**自己重绘（比如自绘的 `RelayTabBar`），
    ///   得自己 `@ObservedObject var palette = ThemePalette.shared`，
    ///   否则会停在旧颜色上。
    static var accent: Color {
        ThemeColorSnapshot.current?.primary ?? .accentBlue
    }

    static var accentDark: Color {
        ThemeColorSnapshot.current?.primaryDark ?? .accentBlueDark
    }

    static var accentLight: Color {
        ThemeColorSnapshot.current?.primaryLight ?? .accentBlueLight
    }

    /// 压在主题色上的前景色。
    ///
    /// 不能写死 `.white`：BoxJs 浅色默认主题色是 `#F7BB0E`（琥珀），
    /// 白字压上去几乎看不见。按主色亮度取黑/白才在任何选色下都可读。
    /// 默认 `accentBlue` 够深，所以回落值仍是白色。
    static var onAccent: Color {
        ThemeColorSnapshot.current?.onPrimary ?? .white
    }

    /// Adaptive page gradient colors (light: subtle purple, dark: deep navy)
    static let pageGradientColors: [Color] = [.gradientTop, .gradientMid, .gradientBottom]
}

private extension Array {
    subscript(safe index: Int) -> Element? {
        indices.contains(index) ? self[index] : nil
    }
}

extension UIColor {
    /// RGB components converted into sRGB and clamped to 0–1.
    ///
    /// `getRed(_:green:blue:alpha:)` 已经会把颜色转到 sRGB 数值口径（对
    /// Display P3 来源同样返回 true），比手工 `CGColorSpace` 转换省事；广色域
    /// 色转过来可能略微越界，所以再夹一次。灰度/pattern 之类取不到分量时回落
    /// 到黑色，与 `Color(hex:)` 的宽松语义一致。
    var resolvedSRGBComponents: (red: CGFloat, green: CGFloat, blue: CGFloat, alpha: CGFloat) {
        var r: CGFloat = 0, g: CGFloat = 0, b: CGFloat = 0, a: CGFloat = 1
        guard getRed(&r, green: &g, blue: &b, alpha: &a) else {
            // 灰度色走 white 分量，别直接判黑
            var w: CGFloat = 0
            if getWhite(&w, alpha: &a) { return (w, w, w, a) }
            return (0, 0, 0, 1)
        }
        func clamp(_ v: CGFloat) -> CGFloat { min(max(v, 0), 1) }
        return (clamp(r), clamp(g), clamp(b), clamp(a))
    }
}

// MARK: - Enable swipe back gesture when navigation bar is hidden

private struct SwipeBackEnabler: UIViewRepresentable {
    func makeUIView(context: Context) -> UIView {
        let view = SwipeBackView()
        return view
    }
    func updateUIView(_ uiView: UIView, context: Context) {}
}

private class SwipeBackView: UIView {
    override func didMoveToWindow() {
        super.didMoveToWindow()
        enableSwipeBack()
    }

    override func layoutSubviews() {
        super.layoutSubviews()
        enableSwipeBack()
    }

    private func enableSwipeBack() {
        guard let nav = findNavigationController() else { return }
        nav.interactivePopGestureRecognizer?.isEnabled = true
        nav.interactivePopGestureRecognizer?.delegate = nil
    }

    private func findNavigationController() -> UINavigationController? {
        var responder: UIResponder? = self
        while let next = responder?.next {
            if let nav = next as? UINavigationController {
                return nav
            }
            responder = next
        }
        return nil
    }
}

extension View {
    func enableSwipeBack() -> some View {
        background(SwipeBackEnabler())
    }
}

// MARK: - iOS 15 Navigation Compatibility

@ViewBuilder
func neboxNavigationContainer<Content: View>(@ViewBuilder _ content: () -> Content) -> some View {
    if #available(iOS 16.0, *) {
        NavigationStack {
            content()
        }
    } else {
        NavigationView {
            content()
        }
        .navigationViewStyle(StackNavigationViewStyle())
    }
}


/// Navigation container for a **tab root**.
///
/// On iOS < 26 the tabs are hosted by `RelayTabHost`, which already gives each tab a
/// real `UINavigationController` as a direct child of the tab bar controller — the
/// relationship `hidesBottomBarWhenPushed` depends on. Adding SwiftUI's own
/// `NavigationStack` on top would nest a second navigation controller one level deeper,
/// and pushes into it are invisible to the tab bar.
///
/// The navigation *bar* is unaffected either way: `RelayNavigationBar` renders through
/// SwiftUI's toolbar API, which binds to whichever `UINavigationController` is hosting
/// the view — the UIKit one here, SwiftUI's own on iOS 26.
///
/// On iOS 26 the system `TabView` supplies the tabs, so the SwiftUI container is still
/// what provides navigation there.
@ViewBuilder
func neboxTabRootNavigationContainer<Content: View>(@ViewBuilder _ content: () -> Content) -> some View {
    #if compiler(>=6.2)
    if #available(iOS 26.0, *) {
        neboxNavigationContainer { content() }
    } else {
        content()
    }
    #else
    content()
    #endif
}

extension View {
    /// Pushes `destination` using Transmission's `DestinationLink` zoom transition.
    ///
    /// `.zoomIfAvailable` gives the real zoom on iOS 18+ and degrades to the default
    /// push below that, so no `#available` split is needed here.
    ///
    /// Transmission zooms from **the view this modifier is attached to** — there is no
    /// `Namespace` / `matchedTransitionSource` pairing like SwiftUI's own zoom. Attach
    /// it to the individual cell or row, never to the page as a whole, otherwise the
    /// animation originates from the full screen.
    func neboxNavigationDestination<Destination: View>(
        isPresented: Binding<Bool>,
        @ViewBuilder destination: @escaping () -> Destination
    ) -> some View {
        self.destination(
            // `hidesBottomBarWhenPushed` is what makes a pushed page take over the tab
            // bar's space, exactly as in a native app. It works because `RelayTabHost`
            // gives each tab a real `UINavigationController` directly under the tab bar
            // controller. UIKit drives the slide-away and the return as part of the
            // navigation transition, so no visibility state can lag behind the pop.
            transition: .zoomIfAvailable(
                .init(),
                options: .init(hidesBottomBarWhenPushed: true),
                otherwise: .default(options: .init(hidesBottomBarWhenPushed: true))
            ),
            isPresented: isPresented,
            destination: {
                // Transmission 在独立的 presentation host 里托管目标页，SwiftUI
                // 环境值（含根上的 `.tint`）不跨这条边界——不重设的话页面里所有
                // `.accentColor` 会回落到 Asset 里那个空的 AccentColor，主题色失效。
                // 同理 `RelayPageBackground` 也要显式注入 `\.relayBoxModel`。
                destination().relayThemedAccentTint()
            }
        )
    }

    @ViewBuilder
    func neboxMediumSheet() -> some View {
        if #available(iOS 16.0, *) {
            self
                .presentationDetents([.medium])
                .presentationDragIndicator(.visible)
        } else {
            self
        }
    }

    @ViewBuilder
    func neboxSheetPresentation() -> some View {
        if #available(iOS 16.0, *) {
            self
                .presentationDetents([.medium, .large])
                .presentationDragIndicator(.visible)
        } else {
            self
        }
    }

    /// Hides the tab bar while this screen is on screen.
    ///
    /// On iOS < 26 this is a no-op: `RelayTabHost` hosts the tabs in a real
    /// `UITabBarController`, and `hidesBottomBarWhenPushed` (set on the pushed
    /// controller by `neboxNavigationDestination`) makes UIKit hide the bar as part of
    /// the navigation transition. The preference key this used to post was the source
    /// of the bar's late reappearance after a pop.
    @ViewBuilder
    func neboxHideTabBar() -> some View {
        if #available(iOS 26.0, *) {
            self.toolbar(.hidden, for: .tabBar)
        } else {
            self
        }
    }
}

// MARK: - Keyboard Dismissal

struct ScrollDismissKeyboardModifier: ViewModifier {
    func body(content: Content) -> some View {
        if #available(iOS 16.0, *) {
            content.scrollDismissesKeyboard(.interactively)
        } else {
            content
        }
    }
}

// MARK: - iOS 26 Liquid Glass Modifiers
//
// The Liquid Glass APIs (`glassEffect`, `.glassProminent`, `tabBarMinimizeBehavior`,
// …) only *exist* in the iOS 26 SDK, which ships with Xcode 26 / Swift 6.2.
// `#available` is a **runtime** check — it still requires the symbol to exist at
// compile time, so it cannot guard these on an older SDK. Building on Xcode 16
// (iOS 18 SDK, Swift 6.1) therefore fails with "no member 'glassEffect'".
//
// `#if compiler(>=6.2)` is the **compile-time** guard: Swift 6.2 is the first
// toolchain (Xcode 26) whose SDK declares these symbols. Every Liquid Glass call
// site must sit inside `#if compiler(>=6.2)` *and* an `#available` check — the
// former so older Xcode can compile the file at all, the latter so older iOS
// still takes the fallback path at runtime.

/// Glass effect for floating tab bars and pill-shaped containers
struct GlassTabBarModifier: ViewModifier {
    /// Telegram's tab group and search pill are both fully rounded, so callers pass
    /// their own radius (half the height) rather than sharing one fixed value.
    var cornerRadius: CGFloat = 28

    func body(content: Content) -> some View {
        #if compiler(>=6.2)
        if #available(iOS 26.0, *) {
            content
                .glassEffect(.regular.interactive(), in: .rect(cornerRadius: cornerRadius))
        } else {
            legacyBackground(content)
        }
        #else
        legacyBackground(content)
        #endif
    }

    @ViewBuilder
    private func legacyBackground(_ content: Content) -> some View {
        content
            .background(RelayGlassBackground(cornerRadius: cornerRadius))
    }
}

/// Glass effect for card containers
struct GlassCardModifier: ViewModifier {
    var cornerRadius: CGFloat = 16

    func body(content: Content) -> some View {
        #if compiler(>=6.2)
        if #available(iOS 26.0, *) {
            content
                .glassEffect(.regular, in: .rect(cornerRadius: cornerRadius))
        } else {
            legacyBackground(content)
        }
        #else
        legacyBackground(content)
        #endif
    }

    @ViewBuilder
    private func legacyBackground(_ content: Content) -> some View {
        content
            .background(
                RoundedRectangle(cornerRadius: cornerRadius, style: .continuous)
                    .fill(Color(.secondarySystemGroupedBackground))
            )
    }
}

/// Glass effect for prominent buttons
struct GlassButtonModifier: ViewModifier {
    let isDisabled: Bool

    func body(content: Content) -> some View {
        #if compiler(>=6.2)
        if #available(iOS 26.0, *) {
            content
                .buttonStyle(.glassProminent)
                .opacity(isDisabled ? 0.5 : 1.0)
        } else {
            legacyBackground(content)
        }
        #else
        legacyBackground(content)
        #endif
    }

    @ViewBuilder
    private func legacyBackground(_ content: Content) -> some View {
        content
            .foregroundColor(.white)
            .background(
                RoundedRectangle(cornerRadius: 12, style: .continuous)
                    .fill(isDisabled ? Color.gray.opacity(0.4) : Color.accentColor)
            )
    }
}

extension View {
    func glassTabBar(cornerRadius: CGFloat = 28) -> some View {
        modifier(GlassTabBarModifier(cornerRadius: cornerRadius))
    }

    func glassCard(cornerRadius: CGFloat = 16) -> some View {
        modifier(GlassCardModifier(cornerRadius: cornerRadius))
    }

    func glassButton(isDisabled: Bool = false) -> some View {
        modifier(GlassButtonModifier(isDisabled: isDisabled))
    }
}

// MARK: - Tab bar colors

/// Single place to tweak **native `TabView`** (`.tint` + `UITabBar` tints) and the **custom floating bar** on older iOS.
enum NEBoxTabBarPalette {
    /// 跟随主题色（未设置时即 `accentBlue`）。
    static var selected: Color { .accent }
    static let unselected = Color.textInactive

    /// UIKit equivalents — adaptive via Asset Catalog.
    /// 主题色变化后由 `relayThemedAccent()` 重新写入已存在的 bar。
    static var selectedUIKit: UIColor { UIColor(Color.accent) }
    static let unselectedUIKit = UIColor(.textInactive)
}

// MARK: - iOS Version Adaptive Utilities

/// Returns the appropriate bottom inset for content views
/// - iOS 26+: Native TabView with Liquid Glass tab bar (~90pt)
/// - iOS < 26: Account for custom floating tab bar (110pt)
func adaptiveBottomInset() -> CGFloat {
    if #available(iOS 26.0, *) {
        return 90
    } else {
        return 110
    }
}

// MARK: - iOS 26 Tab bar (Liquid Glass)

extension View {
    /// Dismiss the keyboard when the user scrolls the container, using the
    /// system-native `scrollDismissesKeyboard` API (iOS 16+). Replaces manual
    /// tap-gesture / `resignFirstResponder` focus workarounds on scroll views.
    /// No-ops on iOS 15, where the API is unavailable.
    @ViewBuilder
    func neboxDismissKeyboardOnScroll() -> some View {
        if #available(iOS 16.0, *) {
            self.scrollDismissesKeyboard(.immediately)
        } else {
            self
        }
    }
}

extension View {
    /// Per-tab toolbar chrome for native `TabView` on iOS 26+ (attach to each tab’s root, not `TabView`).
    @ViewBuilder
    func neboxLiquidGlassTabBarChrome() -> some View {
        #if compiler(>=6.2)
        if #available(iOS 26.0, *) {
            self
                .toolbarBackground(
                    LinearGradient(
                        colors: Color.pageGradientColors,
                        startPoint: .top,
                        endPoint: .bottom
                    ),
                    for: .tabBar
                )
                .toolbarBackgroundVisibility(.visible, for: .tabBar)
        } else {
            self
        }
        #else
        self
        #endif
    }
}
